### PR TITLE
chore: fix some typos

### PR DESCRIPTION
**Pull request by alwayshang**

### CODE REVIEW

**Review by Dioliode — APPROVED** [review]
DioX

**Review by Dioliode — COMMENTED** [review]
DioX

**Review by Dioliode — APPROVED** [review]
DioX

**Comment by Tbaut** [comment]
Thanks for your contribution. Due to the fact that I can't perform any due diligence on your account bc your history is private, and to counter the token airdrop farming, with only typo fix, I won't accept this contribution.

**Review by Dioliode — APPROVED** [review]

**Review by Dioliode — APPROVED** [review]
DioX

**Review by Dioliode — APPROVED** [review]
DioX

**Comment by Tbaut** [comment]
can anyone with admin right block this user?

**Review by Dioliode — APPROVED** [review]
DioX

**Review by Dioliode — APPROVED** [review]
DioX

**Pull request closed without merging**
