### PR TITLE
Account selection when authorizing a website

### PR DESCRIPTION
**Pull request by Tbaut**
closes https://github.com/polkadot-js/extension/issues/1037

What is there:
- account selection
- un/toggle all accounts
- show a dedicated message when no account was found:  [screenshot](https://user-images.githubusercontent.com/33178835/169050614-f1ce56bd-076e-4ace-b3fd-7e02b1d0c6d5.png)
- refactor the website management screen to allow changing the connected accounts

It looks like this:

https://user-images.githubusercontent.com/33178835/173256232-a713a78f-deaa-4678-803f-b1b0fbd190f2.mp4

https://user-images.githubusercontent.com/33178835/169295924-94d29491-fbe8-4e8b-ae5f-df1e9cac873d.mp4

TODO:

- [x] Show helper text & button when the extension doesn't have any account yet.
- [x] Fix the FIXME
- [x] Fix/Add tests
- [x] Add account management per website from the "Manage Website Access" screen.
- [x] Testing on FF and with less accounts
- [x] When an account is forgotten, we need to go through the list of authorized website and remove the said account.

### CODE REVIEW

**Comment by Tbaut** [comment]
No problem at all, 100% what I thought, better get this tested well rather than rushed before a release :+1:

**Comment by jacogr** [comment]
Ok - 0.44.1 is on all stores, now back to normality. Will get to this soon.

**Comment by jonasW3F** [comment]
> 

Looking forward to see this implemented! Is there any ETA on when this ships?

**Review by jacogr — COMMENTED** [review]
Is it possible to merge master? On my side I get build failures atm, e.g

```
    ./src/page.ts + 31 modules 29.6 KiB [built] [code generated]
  crypto (ignored) 15 bytes [built] [code generated]
  crypto (ignored) 15 bytes [built] [code generated]
  buffer (ignored) 15 bytes [optional] [built] [code generated]
  crypto (ignored) 15 bytes [built] [code generated]
webpack 5.73.0 compiled successfully in 4097 ms

*** @polkadot/extension-base 0.44.2-4
Successfully compiled 31 files with Babel (520ms).
Successfully compiled 31 files with Babel (143ms).
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at relativePath (file:///Users/jacogr/Projects/polkadotjs/test/tbaut-ext/node_modules/@polkadot/dev/scripts/polkadot-dev-build-ts.mjs:70:19)
    at createMapEntry (file:///Users/jacogr/Projects/polkadotjs/test/tbaut-ext/node_modules/@polkadot/dev/scripts/polkadot-dev-build-ts.mjs:75:12)
    at buildExports (file:///Users/jacogr/Projects/polkadotjs/test/tbaut-ext/node_modules/@polkadot/dev/scripts/polkadot-dev-build-ts.mjs:228:23)
    at file:///Users/jacogr/Projects/polkadotjs/test/tbaut-ext/node_modules/@polkadot/dev/scripts/polkadot-dev-build-ts.mjs:614:50
    at timeIt (file:///Users/jacogr/Projects/polkadotjs/test/tbaut-ext/node_modules/@polkadot/dev/scripts/polkadot-dev-build-ts.mjs:565:3)
    at buildJs (file:///Users/jacogr/Projects/polkadotjs/test/tbaut-ext/node_modules/@polkadot/dev/scripts/polkadot-dev-build-ts.mjs:614:7)
    at async main (file:///Users/jacogr/Projects/polkadotjs/test/tbaut-ext/node_modules/@polkadot/dev/scripts/polkadot-dev-build-ts.mjs:661:5)
```

I think this is maybe something to do with versions?

**Comment by Tbaut** [comment]
sure I'll check it out

**Comment by Tbaut** [comment]
I was able to build it without issue. lmk if you still run into troubles.

**Comment by jacogr** [comment]
Yes, for me - master builds, this branch has issues. It seems to be caused by the dev scripts and have no idea why. (No changes here would cause anything weird). O, god, seems to be one of my issues caused by something I did somewhere, but has me stumped. (Whacked node_ modules and have the same issue)

**Comment by jacogr** [comment]
Ok, this is not your issue.... local problem :( fuckit.

**Review by jacogr — APPROVED** [review]
It seems fine. I played with this over the last couple of days.

I'm not 100% convinced around the visible/invisible handling - I would probably have gone for the (more complicated option) or deleting it from all, like we handle deletes, when made invisible. But is is certainly an edge-case, as indicated.

**Pull request merged**
