### PR TITLE
Add list of ethereum networks

### PR DESCRIPTION
**Pull request by joelamouche**
Unfortunately, I forgot to add Moonriver, so the extension compatibility only works with Moonbase Alpha...
@jacogr let me know if you can think of a better place to store this list (it is not the same as `import { ethereumChains } from '@polkadot/apps-config';`, which is runtime specname whereas in the extension it is the chain name)

### CODE REVIEW

**Comment by jacogr** [comment]
With the release cadence of the extension (it is purposefully really slow - (a) the approval process is not simple, (b) it requires a lot of testing and cannot be rushed), no sure a hard-coded list is going to work. 

Maybe the correct approach i to rather use the `isEthereum` that is passed as part of the metadata updates? That will always be current for chains that has been added at least once via metadata. (And we can warn if the chain being created for doesn't have any updated metadata as part of the creation process)

We can certainly still use a list as a fallback for known where there has been no metadata supplied, but would rather not rely on it as the be-all and end-all. Thoughts?

**Comment by joelamouche** [comment]
> Thoughts?

Ok yes good idea. My plan is to use the chainType from metadata and a hardcoded list as fallback

**Comment by joelamouche** [comment]
I want to add this feature: https://github.com/polkadot-js/extension/issues/837

**Comment by joelamouche** [comment]
@jacogr 
With the ethereum (bip44) derivation path, the button is too low to be seen
Screenshot 2021-09-23 at 15 40 13
How can I change the window size or make it scrollable?
Also I want to hide the derivation path components in an Expander, as it is done in the polkadot-js app, but that component is only in `@polkadot/react-components`.
Should I :
- import from `@polkadot/react-components`
- add it to extension components
- other

**Comment by joelamouche** [comment]
@jacogr pls review when you get the opportunity

**Comment by joelamouche** [comment]
@jacogr please take the time to respond to my comment https://github.com/polkadot-js/extension/pull/834#issuecomment-925828782 when you have the time

**Comment by joelamouche** [comment]
@jacogr please take the time to respond to my comment #834 (comment) when you have the time

**Comment by crystalin** [comment]
@jacogr ,as the launch of parachain on Polkadot is coming soon, it'd be great if we can offer support of polkadotjs extension.

**Comment by jacogr** [comment]
Replaced by https://github.com/polkadot-js/extension/pull/882

(doesn't contain hard-coded lists, rather relies on the chain type in the metadata. Tested on Moonriver for both import and new creation)

**Comment by joelamouche** [comment]
@jacogr Thanks! What about the CreateEthDerivationPath component? Using ethereum stye derivation with derivation path is important because people are creating addresses with the wrong derivation

**Comment by jacogr** [comment]
100%, that should be added.

**Comment by jacogr** [comment]
That would make 100% sense.

**Pull request closed without merging**
