### PR TITLE
chore: Update XCM Analyser to -> v1.2.1

### PR DESCRIPTION
**Pull request by dudo50**
This PR features an update to XCM-Analyser to the v1.2.1 - version with a proper readme. No changes to the code, so compatible right away.

With kind regards
Team ParaSpell

### CODE REVIEW

**Review by TarikGul — CHANGES_REQUESTED** [review]
Apologies for the delay, just the conflicts need to be resolved.

**Comment by dudo50** [comment]
@TarikGul No worries, feel free to close this PR and bump version manually. Should be easier way to resolve conflicts :).

With kind regards,
Team ParaSpell

**Comment by dudo50** [comment]
Hey @TarikGul , the dependencies should now be resolved. Let us know if there is anything else needed from our side. Thanks!

**Comment by dudo50** [comment]
Closing this in favor of newer version.

**Pull request closed without merging**
