### PR TITLE
[DRAFT] feat: extension-rpc

### PR DESCRIPTION
**Pull request by ryanleecode**
Extract the RPC methods outside of `extension-ui` so they can be used elsewhere i.e. the content script.

### CODE REVIEW

**Comment by TarikGul** [comment]
cc: @Tbaut

**Comment by Tbaut** [comment]
Can I ask why this PR? What's the benefit of doing this, or why is it needed?

**Comment by ryanleecode** [comment]
i need to access the list of accounts and createTx function in the content script / inpage. 

note: this is still a draft and not final yet; might even scrap this all together

**Comment by Tbaut** [comment]
But can you tell why? This is not linked to any issue, so there's no background info about why this change is needed.

**Comment by ryanleecode** [comment]
We won't be needing this. 

short answer for why is we are testing out the [@substrate/discovery protocol](https://github.com/paritytech/substrate-connect/tree/main/packages/discovery). There will be a forum post explaining this in the near future.

**Pull request closed without merging**
