### PR TITLE
Add custom eth derivation path

### PR DESCRIPTION
**Pull request by joelamouche**
- Move Network Dropdown to first step since it determines address derivation
- Add custom Eth derivation path for ethereum parachains
  - for address creation
  - for address import from seed
- Remove derivation feature for ethereum addresses (not compatible with bip 44)

Tackles #836

### CODE REVIEW

**Comment by joelamouche** [comment]
@jacogr This is ready for review but I dont know how to fix the lint

**Comment by joelamouche** [comment]
@jacogr lmk if you know how to fix the linter

**Review by mrcali213 — APPROVED** [review]

**Comment by joelamouche** [comment]
@jacogr ready for review

**Comment by joelamouche** [comment]
@jacogr ready for review

**Comment by joelamouche** [comment]
@jacogr updated and ready for review

**Comment by joelamouche** [comment]
@jacogr fixed and ready for review

**Comment by joelamouche** [comment]
@jacogr pls review this when you have the time

**Review by JurbinM — APPROVED** [review]

**Pull request closed without merging**
